defaultViewKey : ""
defaultViewPass : ""
defaultViewSecret : ""

bitcoinViewKey : ""
bitcoinViewPass : ""
bitcoinViewSecret : ""

etheriumViewKey : ""
etheriumViewPass : ""
etheriumViewSecret : ""