defaultViewKey : ""
defaultViewPass : ""
defaultViewSecret : ""

bitcoinViewKey : ""
bitcoinViewPass : ""
bitcoinViewSecret : ""

etheriumViewKey : ""
etheriumViewPass : ""
etheriumViewSecret : ""

defaultEthID : ""
defaultBtcID : ""

btcBtcID : ""
btcSolID : ""
btcAtomID : ""
btcAlgoID : ""
btcDotID : ""
btcXtzID : ""

ethEthID : ""
ethAdaID : ""
ethLinkID : ""
ethBatID : ""
ethManaID : ""
ethSushiID : ""